version: '3.1'
services:

  personblog:
    build: .
    container_name: personblog
    ports:
      - 8080:8080
    networks:
      - blog_network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /Users/tommy/data/myscript/:/docker-entrypoint-initdb.d/
    networks:
      - blog_network
    environment:
      MYSQL_ROOT_PASSWORD: Tsyw@110

  redis:
    image: redis
    restart: always
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - blog_network
    volumes:
      - $PWD/data:/data
      - /Users/tommy/redis.conf:/usr/local/etc/redis/redis.conf
networks:
  blog_network:
    driver: bridge
